baseURL = "https://cloudresumechallenge.dev/"
languageCode = "en-us"
title = "The Cloud Resume Challenge"
description = "A proven way to advance your cloud career - in just 16 steps."
images = ['images/book.png']
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true
googleAnalytics = "UA-128893913-3"

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Success Stories"
    weight = 4
    url = "halloffame/"
[[menu.main]]
    name = "Get The Book"
    weight = 2
    url = "book/"
[[menu.main]]
    name = "Get Hired"
    weight = 3
    url = "newsletter/"
[[menu.main]]
    name = "Take The Challenge"
    weight = 1
    url = "docs/the-challenge"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "Forrest Brazeal"
  searchPlaceholder = "Search ..."
  mobileNavigation = "left"
  enableSearch = false
  uniqueHomePage = true
  enableDarkMode = true

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "images/logo.svg"
    darkMode = "images/logo.svg"